### ISSUE TITLE
Default currency?

### ISSUE THREAD

**Issue by johnkeyler** [KosyanMedia/Aviasales-iOS-SDK#52]
Hello;

Is that possible to set a default currency for localized items.

So for french language: set to > EUR currency

For norwegian set to > NOK

All of them are USD now without looking to the default language.

Thank you!

**Comment by chebotovanton** [comment]
Hello.

Default currency is selected based on system locale currency identifier. Not the language. Since user can select language and region separately. And system keeps user' locale in region settings.

Here's some code from InteractionManager class:

```
let currencyCode = Locale.current.currencyCode ?? ""
currency = CurrencyManager.shared.getCurrency(withCode: currencyCode) ??
 CurrencyManager.shared.defaultCurrency()
```

And take a look at Region Format Example in the bottom of this:
![img_8592](https://user-images.githubusercontent.com/4598475/28779646-9d03c1d2-760c-11e7-96a2-55310537958e.PNG)

Russia's selected as Region. So there are rubles (RUB), no matter the English language as a default.

**Comment by johnkeyler** [comment]
Hello;

Thank you for your reply. I have changed the local settings and the language but the default currency is still USD. I mean it's not changing the currency. Should i add the code above or the original one has that feature?

Thank you!

**Comment by chebotovanton** [comment]
The code is from the original one. No need to do any additional work. Do you reinstall app after region switch? App detects the region and sets the default currency after first launch only. (According to hypothesis users don't change the locale all the time 😄 )

**Comment by johnkeyler** [comment]
Hmm looks like i have selected non supported language, that may be the reason.

I will have a look and let you know!

**Comment by johnkeyler** [comment]
I think you guys increase the number of currencies, because much of them are missing:)

**Comment by geekkon** [comment]
New release 3.1.0 supports almost all currencies. You can try it!
